# Generated by Django 2.2.10 on 2021-08-16 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkPlace',
        ),
    ]
