# Generated by Django 3.2.2 on 2021-05-26 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of category')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='White_wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование продукции')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='Цена')),
                ('spirit_type', models.CharField(max_length=255, verbose_name='Категория:')),
                ('region', models.CharField(max_length=255, verbose_name='Регион производства:')),
                ('vintage', models.CharField(max_length=10, verbose_name='Винтаж:')),
                ('alcohol', models.CharField(max_length=10, verbose_name='Крепость`:')),
                ('value', models.CharField(max_length=10, verbose_name='Объём:')),
                ('grape', models.CharField(max_length=255, verbose_name='Виноград')),
                ('color', models.CharField(max_length=255, verbose_name='Цвет:')),
                ('flavour', models.CharField(max_length=255, verbose_name='Аромат`:')),
                ('taste', models.CharField(max_length=255, verbose_name='Вкус:')),
                ('body', models.CharField(max_length=10, verbose_name='Тело')),
                ('gastronomic', models.CharField(max_length=13, verbose_name='Гастрономическое сочетание:')),
                ('serving', models.CharField(max_length=255, verbose_name='Температура сервировки:')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='Производитель:')),
                ('manufacturer_site', models.CharField(max_length=255, verbose_name='Сайт производителя')),
                ('provider', models.CharField(max_length=255, null=True, verbose_name='Поставщик:')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rose_wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование продукции')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='Цена')),
                ('spirit_type', models.CharField(max_length=255, verbose_name='Категория:')),
                ('region', models.CharField(max_length=255, verbose_name='Регион производства:')),
                ('vintage', models.CharField(max_length=10, verbose_name='Винтаж:')),
                ('alcohol', models.CharField(max_length=10, verbose_name='Крепость`:')),
                ('value', models.CharField(max_length=10, verbose_name='Объём:')),
                ('grape', models.CharField(max_length=255, verbose_name='Виноград')),
                ('color', models.CharField(max_length=255, verbose_name='Цвет:')),
                ('flavour', models.CharField(max_length=255, verbose_name='Аромат`:')),
                ('taste', models.CharField(max_length=255, verbose_name='Вкус:')),
                ('body', models.CharField(max_length=10, verbose_name='Тело')),
                ('gastronomic', models.CharField(max_length=13, verbose_name='Гастрономическое сочетание:')),
                ('serving', models.CharField(max_length=255, verbose_name='Температура сервировки:')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='Производитель:')),
                ('manufacturer_site', models.CharField(max_length=255, verbose_name='Сайт производителя')),
                ('provider', models.CharField(max_length=255, null=True, verbose_name='Поставщик:')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Red_wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование продукции')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='Цена')),
                ('spirit_type', models.CharField(max_length=255, verbose_name='Категория:')),
                ('region', models.CharField(max_length=255, verbose_name='Регион производства:')),
                ('vintage', models.CharField(max_length=10, verbose_name='Винтаж:')),
                ('alcohol', models.CharField(max_length=10, verbose_name='Крепость`:')),
                ('value', models.CharField(max_length=10, verbose_name='Объём:')),
                ('grape', models.CharField(max_length=255, verbose_name='Виноград')),
                ('color', models.CharField(max_length=255, verbose_name='Цвет:')),
                ('flavour', models.CharField(max_length=255, verbose_name='Аромат`:')),
                ('taste', models.CharField(max_length=255, verbose_name='Вкус:')),
                ('body', models.CharField(max_length=10, verbose_name='Тело')),
                ('gastronomic', models.CharField(max_length=13, verbose_name='Гастрономическое сочетание:')),
                ('serving', models.CharField(max_length=255, verbose_name='Температура сервировки:')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='Производитель:')),
                ('manufacturer_site', models.CharField(max_length=255, verbose_name='Сайт производителя')),
                ('provider', models.CharField(max_length=255, null=True, verbose_name='Поставщик:')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Champagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование продукции')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='Цена')),
                ('spirit_type', models.CharField(max_length=255, verbose_name='Категория:')),
                ('country_of_manufacturing', models.CharField(max_length=255, verbose_name='Страна производства')),
                ('region', models.CharField(max_length=255, verbose_name='Регион производства:')),
                ('vintage', models.CharField(max_length=10, verbose_name='Винтаж:')),
                ('alcohol', models.CharField(max_length=10, verbose_name='Крепость`:')),
                ('value', models.CharField(max_length=10, verbose_name='Объём:')),
                ('grape', models.CharField(max_length=255, verbose_name='Виноград')),
                ('color', models.CharField(max_length=255, verbose_name='Цвет:')),
                ('flavour', models.CharField(max_length=255, verbose_name='Аромат`:')),
                ('taste', models.CharField(max_length=255, verbose_name='Вкус:')),
                ('body', models.CharField(max_length=10, verbose_name='Тело')),
                ('gastronomic', models.CharField(max_length=13, verbose_name='Гастрономическое сочетание:')),
                ('serving', models.CharField(max_length=255, verbose_name='Температура сервировки:')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='Производитель:')),
                ('manufacturer_site', models.CharField(max_length=255, verbose_name='Сайт производителя')),
                ('provider', models.CharField(max_length=255, null=True, verbose_name='Поставщик:')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
