# Generated by Django 3.2.2 on 2021-05-27 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champagne',
            name='alcohol',
            field=models.CharField(max_length=10, verbose_name='Крепость:'),
        ),
        migrations.AlterField(
            model_name='champagne',
            name='flavour',
            field=models.CharField(max_length=255, verbose_name='Аромат:'),
        ),
        migrations.AlterField(
            model_name='red_wine',
            name='alcohol',
            field=models.CharField(max_length=10, verbose_name='Крепость:'),
        ),
        migrations.AlterField(
            model_name='red_wine',
            name='flavour',
            field=models.CharField(max_length=255, verbose_name='Аромат:'),
        ),
        migrations.AlterField(
            model_name='rose_wine',
            name='alcohol',
            field=models.CharField(max_length=10, verbose_name='Крепость:'),
        ),
        migrations.AlterField(
            model_name='rose_wine',
            name='flavour',
            field=models.CharField(max_length=255, verbose_name='Аромат:'),
        ),
        migrations.AlterField(
            model_name='white_wine',
            name='alcohol',
            field=models.CharField(max_length=10, verbose_name='Крепость:'),
        ),
        migrations.AlterField(
            model_name='white_wine',
            name='flavour',
            field=models.CharField(max_length=255, verbose_name='Аромат:'),
        ),
    ]
