# Generated by Django 2.2.10 on 2021-07-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_post_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='short_description',
            field=models.CharField(default='', max_length=50, verbose_name='Краткое описание поста'),
        ),
    ]
