# Generated by Django 2.2.10 on 2021-08-16 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitter',
            name='combination',
            field=models.CharField(max_length=255, verbose_name='Сочитается с:'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='combination',
            field=models.CharField(max_length=255, verbose_name='Сочитается с:'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mainapp.Post'),
        ),
        migrations.AlterField(
            model_name='gin',
            name='combination',
            field=models.CharField(max_length=255, verbose_name='Сочитается с:'),
        ),
        migrations.AlterField(
            model_name='liquor',
            name='combination',
            field=models.CharField(max_length=255, verbose_name='Сочитается с:'),
        ),
        migrations.AlterField(
            model_name='mezcal',
            name='combination',
            field=models.CharField(max_length=255, verbose_name='Сочитается с:'),
        ),
        migrations.AlterField(
            model_name='porto',
            name='gastronomic',
            field=models.TextField(max_length=255, verbose_name='Гастрономическое сочетание:'),
        ),
        migrations.AlterField(
            model_name='red_wine',
            name='gastronomic',
            field=models.TextField(max_length=255, verbose_name='Гастрономическое сочетание:'),
        ),
        migrations.AlterField(
            model_name='rose_wine',
            name='gastronomic',
            field=models.TextField(max_length=255, verbose_name='Гастрономическое сочетание:'),
        ),
        migrations.AlterField(
            model_name='rum',
            name='combination',
            field=models.CharField(max_length=255, verbose_name='Сочитается с:'),
        ),
        migrations.AlterField(
            model_name='sparkling_wine',
            name='gastronomic',
            field=models.TextField(max_length=255, verbose_name='Гастрономическое сочетание:'),
        ),
        migrations.AlterField(
            model_name='tequila',
            name='combination',
            field=models.CharField(max_length=255, verbose_name='Сочитается с:'),
        ),
        migrations.AlterField(
            model_name='vermouth',
            name='combination',
            field=models.CharField(max_length=255, verbose_name='Сочитается с:'),
        ),
        migrations.AlterField(
            model_name='vodka',
            name='combination',
            field=models.CharField(max_length=255, verbose_name='Сочитается с:'),
        ),
        migrations.AlterField(
            model_name='whiskey',
            name='combination',
            field=models.CharField(max_length=255, verbose_name='Сочитается с:'),
        ),
        migrations.AlterField(
            model_name='white_wine',
            name='gastronomic',
            field=models.TextField(max_length=255, verbose_name='Гастрономическое сочетание:'),
        ),
    ]
