# Generated by Django 2.2.10 on 2021-08-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_auto_20210816_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='workplace',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
