# Generated by Django 2.2.10 on 2021-08-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_profile_workplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitter',
            name='provider2',
            field=models.CharField(max_length=255, null=True, verbose_name='Поставщик:'),
        ),
    ]
