# Generated by Django 2.2.10 on 2021-08-16 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_bitter_provider2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitter',
            name='provider2',
        ),
    ]
