# Generated by Django 3.2.8 on 2021-12-13 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_auto_20211116_0251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktail',
            name='cocktails',
        ),
        migrations.RemoveField(
            model_name='cocktail',
            name='combination',
        ),
        migrations.RemoveField(
            model_name='cocktail',
            name='country_of_manufacturing',
        ),
        migrations.RemoveField(
            model_name='cocktail',
            name='manufacturer_site',
        ),
        migrations.RemoveField(
            model_name='cocktail',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='cocktail',
            name='region',
        ),
        migrations.RemoveField(
            model_name='cocktail',
            name='serving',
        ),
    ]
