# Generated by Django 3.2.8 on 2021-12-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_auto_20211213_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='manufacturer',
            field=models.CharField(max_length=255, verbose_name='История создания:'),
        ),
    ]
