# Generated by Django 4.0 on 2021-12-16 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0033_postviews_remove_post_views_post_slug_delete_ipmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postviews',
            name='IPAddres',
            field=models.GenericIPAddressField(default='45.243.82.169'),
        ),
    ]
