# Generated by Django 4.0 on 2021-12-16 01:34

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('mainapp', '0038_ipmodel_remove_post_post_views_delete_postviews_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipmodel',
            name='blog_views',
        ),
        migrations.AddField(
            model_name='ipmodel',
            name='ip',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
