# Generated by Django 4.0 on 2021-12-16 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0039_remove_ipmodel_blog_views_ipmodel_ip_post_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pub_date',)},
        ),
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
        migrations.DeleteModel(
            name='IpModel',
        ),
    ]
