# Generated by Django 4.0 on 2021-12-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0042_remove_post_views_post_count_views_post_slug_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ip',
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
