# Generated by Django 4.0 on 2021-12-30 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0043_delete_ip_alter_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
