# Generated by Django 3.2.10 on 2021-12-30 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0045_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='count_views',
        ),
    ]
