# Generated by Django 3.2.10 on 2021-12-31 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0047_hitcount_urlhit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HitCount',
        ),
        migrations.DeleteModel(
            name='UrlHit',
        ),
    ]
