# Generated by Django 3.2.10 on 2021-12-31 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0048_auto_20211231_1141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostCountViews',
        ),
    ]
