# Generated by Django 3.2.10 on 2021-12-31 12:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0049_delete_postcountviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.ManyToManyField(related_name='view_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
